package com.sociallunch.android.models;

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Calendar;

public class Suggestion implements Parcelable {
    public Integer id;
    public Venue venue;
    public Calendar meetingTime;

    public Suggestion(Venue venue, Calendar meetingTime) {
        this.id = 1; //TODO-TEMP: to be generated by server-side DB
        this.venue = venue;
        this.meetingTime = meetingTime;

    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel out, int flags) {
        out.writeInt(id);
        out.writeLong(meetingTime.getTimeInMillis());
        out.writeParcelable(venue, flags);
    }

    public static final Parcelable.Creator<Suggestion> CREATOR
            = new Parcelable.Creator<Suggestion>() {
        public Suggestion createFromParcel(Parcel in) {
            return new Suggestion(in);
        }
        public Suggestion[] newArray(int size) {
            return new Suggestion[size];
        }
    };

    public Suggestion(Parcel in) {
        this.id = in.readInt();
        Calendar meetingTime = Calendar.getInstance();
        meetingTime.setTimeInMillis(in.readLong());
        this.meetingTime = meetingTime;
        this.venue = in.readParcelable(Venue.class.getClassLoader());
    }
}
